//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by oglshape.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define ID_DRAW_POINTS                  32771
#define ID_DRAW_LINES                   32772
#define ID_DRAW_LINESTRIP               32773
#define ID_DRAW_LINELOOP                32774
#define ID_DRAW_POLYGONS                32775
#define ID_DRAW_NONCONVEX               32776
#define ID_DRAW_TRIANGLES               32777
#define ID_DRAW_TRIANGLESTRIP           32778
#define ID_DRAW_TRIANGLEFAN             32779
#define ID_DRAW_QUADRILATERALS          32780
#define ID_DRAW_QUADSTRIP               32781

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
